### ISSUE TITLE
training data cannot be downloaded

### ISSUE THREAD

**Issue by youjiawu96** [jhhuangchloe/DiffusionPDE#1]
When I try to access and download the training data zip file, which is about 121GB, the download was unsuccessful with the following error message:
"Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

Is it possible that you share your data with one zip file for one equation to reduce the size of each file? Thanks!

**Comment by jhhuangchloe** [comment]
Hello, we have updated the README file, and all data files can be accessed [here](https://drive.google.com/drive/folders/1YbTCcBE6HlUuYNGuf2QVGfbmfTOi3_My?usp=sharing). Please let us know if this works.

**Comment by youjiawu96** [comment]
Why are there only two records in the test dataset of bounded-ns equation?

**Comment by HoinJung** [comment]
gdown doesn't work for this dataset. Use this,
https://stackoverflow.com/questions/65312867/how-to-download-large-file-from-google-drive-from-terminal-gdown-doesnt-work

If the session stops during downloading, add this command, 
 --http1.1
